[files]
ignore-files = true
ignore-hidden = false
extend-exclude = [
    ".git/",
    "bicore/go.mod",
    "bicore/go.sum",
    "bicore/go.work.sum",
]


[default]
extend-ignore-re=[
    "ios_54d9b18d8e7a4caf9d149573e16480ba",
    "Pn",
    "SIZ9",
    "alo",
    "ot",
    "[Cc]ummulative",
    "OTU",
    "[Tt]ransfered",
]
check-filename = true




